# Generated by Django 5.0.2 on 2024-02-22 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="scheduled_time",
        ),
        migrations.AddField(
            model_name="post",
            name="post_id",
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name="post",
            name="author",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="post",
            name="title",
            field=models.CharField(max_length=255),
        ),
    ]
