# Generated by Django 5.0.2 on 2024-02-22 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0002_remove_post_scheduled_time_post_post_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="author",
            field=models.CharField(default="John_doe", max_length=255),
        ),
    ]
