# Generated by Django 5.0.2 on 2024-02-22 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0003_alter_post_author"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="author",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="post",
            name="post_id",
            field=models.IntegerField(default=0),
        ),
    ]
